{% set name = "baseband" %}
{% set version = "4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 467bd22e18f2a47554a1d69b8406acb07587bf18ee39180bd169309efd9ebe23
  patches:
    - baseband.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  noarch: python

requirements:
  host:
    - astropy >=2.0
    - pip
    - python
  run:
    - astropy >=2.0
    - python

test:
  imports:
    - baseband
    - baseband.dada
    - baseband.data
    - baseband.data.gsb
    - baseband.gsb
    - baseband.guppi
    - baseband.helpers
    - baseband.mark4
    - baseband.mark5b
    - baseband.vdif
    - baseband.vlbi_base

about:
  home: https://baseband.readthedocs.io
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A package for radio baseband I/O
  description: |
    Baseband is a package for reading and writing VLBI and other radio
    baseband files, with the aim of simplifying and streamlining data
    conversion and standardization.
  doc_url: https://baseband.readthedocs.io/
  dev_url: https://github.com/mhvk/baseband

extra:
  recipe-maintainers:
    - mwcraig
