{% set name = "baseband" %}
{% set version = "3.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d6b9745d63e4a8a4497311d758161ab974800556aa0348f662ec0595803af5e1
  patches:
    - baseband.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - astropy >=2.0
    - pip
    - python
  run:
    - astropy >=2.0
    - python

test:
  imports:
    - baseband
    - baseband.dada
    - baseband.data
    - baseband.data.gsb
    - baseband.gsb
    - baseband.guppi
    - baseband.helpers
    - baseband.mark4
    - baseband.mark5b
    - baseband.vdif
    - baseband.vlbi_base

about:
  home: https://baseband.readthedocs.io
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: A package for radio baseband I/O
  description: |
    Baseband is a package for reading and writing VLBI and other radio
    baseband files, with the aim of simplifying and streamlining data
    conversion and standardization.
  doc_url: https://baseband.readthedocs.io/
  dev_url: https://github.com/mhvk/baseband

extra:
  recipe-maintainers:
    - mwcraig
