travis:
  secure:
    BINSTAR_TOKEN: NtQtxUGCmeYEHZuDmdo41DrDb1a6WxQpi4FK5fpBIj7+zWNYJD8664if9fCSU+xmThp4LJxloowx7vFeBLKlgUdCGZZPVsr31AZEEQHp68vTucz2Fq2BvWv4Bm4CBJH4ibdftfhYy1DutywQX8W3ONcu+KXJa3dozU0Onsy9pSEKoTUJPcS2QG+U0gyytk58uvL2TcThwNwxzL3rMmY0lcPQWwnfLy2QsyjYs5q+M30bevgl0gbj7YbDLtbHuAT2Ui/fmntSZoo1+ZExskM9Ort0Mk8CYmgynZn1bAZwuiYXRgjHj4kwxObnItx0kYmvErrf47B/791miFyWoLcAaHVU5WKXAi7vgVVnXyshev6Rej1g6RJq6y/4Wb9nuZUByYjjXOzKQfbusaoTCOIxp5LCzt9JEWKnDYXekwpmP3SXEdjmsM7hmoHWJK2SfqmPb4cuM8XzJN0gHy7PZLrHzDLWLOd93D29rku0Txtam6iOYLUvghsQ7CBzvunDz4mrRdoQbx478FOrlfrWq9QOpMA1CBvojw/QK/bUfANk3KiXlOftdnEdvPFzYaxFD6YDM1sccTk+gwWa+j3b9bbcti3yz+CDkG86yIQztmto6eV9jioqlEQNPiyD+5uMHl7Svj0vXVJAG8rOnT3tU4QoUnx1Y63TiBHC0MqTyr0Kv2U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
